# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelNote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelNote
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'GoogleMaps'
   pod 'GooglePlacePicker'
   pod 'GooglePlaces'
   pod 'Alamofire', '~> 4.4'
   pod 'SwiftyJSON'
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'AVOSCloud'
   pod 'JPush'
   pod 'SnapKit', '~> 4.0.0'
end
