#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Wed Apr 17 09:05:35 CST 2019
#define FWConfiguration rlZFhbTOgygJOLoB
#define fwDidFinishLaunchingWithOptions OJnPRxfBHqEaZBYA
#define fwJpushDidReceiveNotificationResponse ExaglQfgPwBGxKOz
#define fwRunOnHomeViewControllerBecomeActive LWSZUgTsFsImeItl
#define fwLanguage lJdWHEGIkvzUvShF
#define urlString owrYCVuDnPzNYLRv
#define weakSelf bpTWdWMmqSDOJovD
#define lcStatus UwKVdlIMjRBpswfv
#define lcUrlString IIhwfpChDVCwqFpc
#define AdvertistingObject YfvRLUFhCoiDMyRZ
#define adWebView uCLMEORtxrwQBjlK
#define AD_DURATION mXJaEJYplsaBbZZA
#define showAdvertistingView HTQLdODyDvJJZOKP
#define removeAdvertistingView YrTyHbGcAUxLwODF
#define trimURL dVWukZpBpTzCwirf
#define sourceString lwlcuSoOlVyBhaPn
#define isChinaArea ghYLvmhCNJZoqJmZ
#define leftConstraint oVGINoOLpXYmsbGX
#define rightConstraint mPHLBOrGDGruhSAK
#define topConstraint tvfmnVTkfyikjqSx
#define bottomConstraint EbXFiKxiRtbMEwEc
#define rmSuperview VApqOlktICkFeTtT
#define destinationString TeMXkowEEhGiBQtE
#define isLanguage JlONrcldZcceKjwE
#define leanCloudAppId fPlzfragTxhMkbrn
#define leanCloudAppKey KrWHBlrDvJnlczgW
#define leanCloudClassName emLSPvjWcofgCBrn
#define leanCloudBoolColumnName PMIIOEOSgosRyYpq
#define leanCloudUrlColumnName BBhhrSNvhQbFsBUd
#define LeanCloudObject KsPkcZKjhAprEfHH
#define getLeanCloudInfo bdBuMkRCunGKXeZt
#define dataQuery1 mvAcXkzcoxZbibIg
#define avObject1 OZtdYVrbnjJPgthp
#define AreaJudge sHzMeeluPVSTYVMD
#define isChinaArea hqbgQVpeCAgdEyRz
#define ChartViewController1 qIpteBAzfivyuizE
#define showAdView jRXVeVLXVyvLaGYs
#define removeAdView rtKNJWQOBIckqrNQ
#define globalIsArea ldHDNwkfPVlyGaOB
#define globalIsEnable zsmIBWtMdhWQJJVb
#define globalMainUrl XFZsgEFHzEzpguXc
#define globalNotificationUrl UHXQwFWlsGtiwDHz
#define description FnDjvvFuCYYvCWBp
#define ClosureWrapper QKBokQskKKhkLulg
#define SwipeGestureRecognizerClosureWrapper OfBnCKbAVVybcpgz
#define Tools QAQbkHdqOcZTqdZe
#define getOutermostView SMMXENIflNcIYwgL
#define getViewOfAbsoluteFame QMHzANFXBbKKkXov
#define originX iZDlPZQgflPlRwyf
#define originY YPGzTITRXWUImUqq
#define startIndicator tbIzkQzJfoDhtzpE
#define indicatorContentView BIBQpXFtBoYjAvpc
#define topCons CZzRihvpJertBlut
#define bottomCons aynNChebtwQQcHtJ
#define leadCons FfAmunESnrSTYQwV
#define trailCons jbFOBbJfjTOgJkJL
#define indicatorView sVxSExftchQEexqQ
#define centerXCons TPONxTRHYfUHFwYx
#define centerYCons DiKYDuVxAofdTmyz
#define cancelBtn THDhsbNGhcxPWewx
#define topCons1 eOOjtOqVwdIWxLBa
#define bottomCons1 QWwLPLRnXubUCANz
#define leadCons1 eTRPLjafaBfshNXH
#define trailCons1 BjHYySIAJtSBYuuX
#define stopIndicator fJcEWnUHQfXCAFXv
#define resizeImageLimited ppjRLmgkHfyHyaeD
#define httpConnect xYrebywKfsInFsgf
#define downloadImage IsldUkBGZePPOPhD
#define downloadJasonDataAsDictionary GivmnnZDAiPDTeKE
#define downloadJasonDataAsArray bzmhkvxQEBbxLIMH
#define backToViewController omOWotxVLZDZcmNz
#define ViewController VFBHEgVqkEwkPRbD
#define StyledPageControl ilqHKPxBSMNUArXz
#define resultArray tkQqwbRHcuMOLdMf
#define adsArray NOWlTCaqAkVVDUgv
#define adScrollView LyYYVEeGUDHPvxVf
#define pageControl CNvZHcSmtBGuVrnT
#define pageControlIsChangingPage eUfgilhvJsylUuhb
#define forward HsQIabalpcUIFjuZ
#define topBarAdUrl alMEPoiHTcTompfc
#define ASIHTTPRequest pzzzfZrUzqGchTIW
#define _currentPage szgwKMqYQsrkLXny
#define tableView kHLbIsYTEamaTNGI
#define httpRequests MURlhEGutJFFBxcA
#define homeButton iWNxzvViCQfRaYNd
#define featureButton RZgDOfTBeLBrFQPQ
#define containerView NSxfsRdNfRxydZTQ
#define mContainerVCArr FxnWOLXrdwyQOwkO
#define mTabBarButtonArr BnNqMfDrxHihvqCw
#define tabBarTitles svSZfQirUuZRfTPN
#define tabBarImages aHHSgFBdcFoTPzfh
#define tabBarColor PrmdUgWcrFGjbkWw
#define tabBarTitleColor QfqNCICKSgskDLzR
#define dataQuery1 MhynFZvnArXILmHI
#define avObject1 tcfKqzoKFFNCczbn
#define adController SrCNlRrNYVPQGtyf
#define language aOTYXVstUqFOXehR
#define dataQuery2 qvpWjrIrbNFqHCzW
#define avObject2 ElBVnkkaYFJVmSRO
#define dest kvUEbJDIiiUwpkJx
#define button01DidTapped INDXJAOlGyyqsgYb
#define storyboard YCjsFwHMaNQtjPiu
#define dVC kMHobSyTgvMHjvQR
#define setBottomTab rwGAfScONEkSbEoy
#define btnViewColor GoxzkneAbRrifZkn
#define btnBgColor dbocNcVqykQgTDnM
#define btnBorderColor NeaVfrKjRdIhbdve
#define btnView01 NYNcOpvseGhECTwn
#define button01 RuZCqEWVdwXhZbEq
#define btnSelectRect TgsSXEtOyiNOQhCA
#define contextSelect CHeGiJGLNTJZzAKx
#define btnSelectColor wjPFHEUqWOzPpuhP
#define btnSelectImage zYQjsVGXEUnXmIOh
#define btnNormalRect QDOSeRzKtJwhCYVQ
#define contextNormal tRLYWdpKuJdkAaKl
#define btnNormalColor hHhboaHonbQysKNV
#define btnNormalImage ajZmEAKXklcudsfe
#define refresh caiSnWBETBovyzQH
#define loadClientInfo iDoYCqkFCVkRdzaP
#define requests ksBfBbIWntsHgvUj
#define request tnVLekssbtCnyDZH
#define responseData yPOcanIMhXepCgDk
#define ret WkjRcMcUyGaZwNdq
#define _result DOStHZlJLjZDzazm
#define loadTopbarAd wGouMevFCufzVDoW
#define loadAds NRfScyZcaeaIjWDg
#define loadMoreData vITaNPdMuypJWfIU
#define loadData uOQnXQttozQaygos
#define urlStr KFLLlwUEmSGfiBTt
#define info ejEREYsFELuHUvBd
#define MyIdentifier MZNLPPMyPTjEITCF
#define detailViewController TwuiYUvSdEDnGybu
#define tOWebViewController yJgDwrQAeYvwyMby
#define bgColor uureclmdCBMRpBVv
#define customView MiAyyNDwzHSmozVP
#define headerLabel tIWxDUXUFUMYgXzE
#define Btn jfeOmbSqvvDIBYsp
#define gotoUrl dOdVZpAGWvdHLpod
#define dd PLKjnTidsADIhwpi
#define buildHeader TfPEcyRwEbjCovOf
#define flash dbDKTEABVJJBhslG
#define setupPage MyZpBbeVecRmUCmC
#define pageWidth McoNmOuydwGhyvvG
#define page fMtrkBURlRPNhYeV
#define changePage DHEUmCorqfRIuBBj
#define pageControlPageDidChange PYTameZbWHapwCPs
#define uploadIDFAData prnAIwOGRDJypSCG
#define _client_id yimCeUxASYqDvHyJ
#define rawData gXbLzFGlYqCCXSTE
#define checkServerStatus ImbmuSJcCiqkSrtP
#define isNeedUpdate kCNvwKBfZYRjtsDi
#define description ymNjtVDDEdEVTSpI
#define alertCtrl VCRZQxSSVhMHCohQ
#define cancelAction qVnblEIjHVHrLjdF
#define confirmAction OuyUJKPheviYjPUJ
#define ADWKWebViewController NofLDDNXeSnTTZtF
#define webViewURL tCfplUckUOcknavN
#define layoutBottomBarHeight ntDeYIAXapFsSvVu
#define hostReachability eHkuCSaXVPTatFHd
#define internetReachability RngSJvViUVuETmVd
#define isLoadFinish dgPckrkmoHXGLzAj
#define isLandscape wqRggTAstEeeobQK
#define wkwebView nDdozLcCwggObwso
#define noNetView REdRAsszGdetrsDw
#define alertView SyRjeLaPmiKzoamq
#define bottomBarView iYzfcijSKtForOsi
#define activityIndicatorView UfLFVXpiSyRpHVEa
#define bottomBarHeightConstraint LoLttwLLmJMfIYKI
#define openSomeTheAppWithWKWebView yJrzyWYFWubpwTzm
#define openOtherAppWithWKWebView zOXhSxZNooAGvfWI
#define whitelist GXGHjpTKIixwiiiS
#define rulesString WahfBRHSKusaOKIz
#define alertController TlYcINwWFQlCUaTw
#define ADReachability tGxPUIIOlCgbOzDU
#define xReachabilityChangedNotification EJNNibNOlweXbGuw
#define reachabilityWithHostName YbHLZgVPruXEyfiP
#define reachabilityWithAddress resfGfHHlmSKboxU
#define reachabilityForInternetConnection ZeIytjjkapZLCaZL
#define startNotifier JIjdNImGTSJakMZd
#define stopNotifier xLWkTmbynmjIJYiT
#define currentReachabilityStatus egUnEMzMWerezqkD
#define connectionRequired gnfenpISweUREWtm
#define PrintReachabilityFlags oHCcIOcoyKrSlUMj
#define ReachabilityCallback OqQIjcFYsphuaUBy
#define noteObject XBKfNiPnRqJwNwsv
#define _reachabilityRef dhyJUXNOegqlYhzI
#define returnValue KblcdKQxlxgQvmCw
#define reachability odKBCBObkhNdmAzy
#define zeroAddress JHCZPJyBPMXNsHfW
#define networkStatusForFlags OaBYYJMqsTKibiAB
#define BaseViewController taysgSYrGBXadofJ
#define BaseTableViewController MymCoBjzUdEMEYBR
#define SideMenuViewController pifioJcFEHxsVKzr
#define HomeViewController bhkHlWetYDqrVvIV
#define HomeTableViewCell UwHkvLUZNttMALXE
#define DataListViewController JtYHlAuLMEzjRyBP
#define BookmarkViewController AaORNZZAiOWmJzJD
#define MoreViewController DEJCDiUCpxoYoCBd
#define MoreAppCell jcBmFdPxOJEGvdOD
#define DetailViewController NWVZllKlFiSCgBBq
#define TOActivityChrome yELjZzjtdiRrtpkW
#define TOActivitySafari WknihjExzdfBcTny
#define TOWebViewController TrkHRuCcJyqtcrIn
#define ISObject BFaogcZLhqliHSYa
#define URLSessionManager dHXPxYZhoCIbosUH
#define ADViewController stnigSKOvydtyKcq
#define ADReachability SRztzkGvUpTziauI
#define trimForURL kQKOXKeGzuuACLfj
#define BsTableViewController WjpNlxuhURkxEhWp
#define ThemeNavigationController WlUqSuEYLhPhrHkq
#define applyTheme GostrmtsUwhpBDOz
#define navigationsetuptest eElgIBZikCNyXfsj
#define refresh AIzECPLbNGbvoNKn
#define setupUI oyTPxnwMoVCRXwYZ
#define createTabButtonWithTitle dnnDqkjtgjQzxiwh
#define updateContainerViewControllers oqhjueTgjFavuYTB
#define mContainerVCArr MTMCOhoUFqNBcKGE
#define mTabBarButtonArr kUyoXSqPyQyXloRt
#define loadAds iFtneIPtyjqizKrB
#define loadPopupAdData bdwJhXZFTmtJJPGZ
#define loadData eEgUTXLwykjwihaG
#define buildHeader cdVIjscnvtXXZyzk
#define isChangeToADViewOK PYmUlukHLBYvUVBC
#define uploadIDFAData YTDbyBKDhOwkrTwR
#define checkServerStatus dWcdnZcrYqcuUUBi
#define ChartViewController1 TQiQjvghKJJCpILf
#define MyQuoteTableViewCell WIqyIAmGyZBzLPtp
#define clickShare AlxDutlvCxQWWyvz
#define label XwxTqWjszmbzuWoE
#define QuoteListTableViewCell VZLzqpeNwmqfzhYn
#define QuoteListTableViewController JjZOSZabyDgvmqHK
#define QuoteTypeTableViewCell vkOoUMlhCdPBWuCk
#define imageView1 ryxfiQudCsuWyMMl
#define image kpQfeuhOOjxxIVQF
#define imageName gtRezUamXkatbBGe
#define footerView dKLzabMrDFEAOLWw
#define SystemPermissionsManager lntrArlohYwWThzg
#define DbViewController zQIOBhbMirfSeWDi
#define JokeTableViewCell ouRiTbyAWQaGPIAy
#define PictureTableViewCell zvbJgamswFCUqYqP
#define JokeTableViewController pqzhPMQGTCesewrD
#define SwiftViewController uBVpQuulavRRXCnz
#endif
